### PR TITLE
ST-166 create orchestration guidelines

### PR DESCRIPTION
**Pull request by piersharding**
Standards, conventions and guidelines for deploying application suites on Container Orchestration technologies

### CODE REVIEW

**Comment by piersharding** [comment]
@flyingfrog81 - I have pushed up the guidelines that I have done so far.  It is approximately 60% done with still some work to go on service, ingress, security, scheduling and finishing the section on the pod.

**Comment by flyingfrog81** [comment]
I think having the TANGO related examples is a great idea

**Comment by piersharding** [comment]
> I think having the TANGO related examples is a great idea

Unfortunately, going here https://github.com/ska-telescope/developer.skatelescope.org/blob/ST-166-create-orchestration-guidelines/src/development/orchestration-guidelines.rst doesn't show the expand/collapse working and some of the other markup.  It does help condense the layout with the large examples.

**Comment by piersharding** [comment]
The orchestration guidelines are now at first draft and ready for review

**Review by flyingfrog81 — APPROVED** [review]
LGTM

**Comment by piersharding** [comment]
Thanks @flyingfrog81 - please merge when you are ready.

**Pull request merged**
