### PR TITLE
Added a skeleton file for the CPP guidelines just to make a start

### PR DESCRIPTION
**Pull request by steve-ord**
Just to get set up to add material and make sure I have the procedures sorted.

### CODE REVIEW

**Comment by flyingfrog81** [comment]
thanks @steve-ord ! 
Do you plan to keep working on this branch or would you request me to merge it as it is? 

I see you have a TODO disclaimer, so that is good enough. In order to get it merged please add relevant instruction to the index page, you can see there is some boilerplate at the beginning of each section. This is used to populate the index on the left bar. 

We try to avoid forking as it makes reviewers life more complicated and also collaboration on PRs harder to achieve. In the future you can work straight in the repo just branching for your new user story.

**Comment by steve-ord** [comment]
@flyingfrog81 It's just an ephemeral branch to test the connections I tried to push the branch to the repo but I dont think I have permissions - hence the fork. 
I could just maintain a SP-124 branch on my GitHub and give the other folks access? I'll do whatever you think is easier to manage at your end.

**Comment by flyingfrog81** [comment]
> @flyingfrog81 It's just an ephemeral branch to test the connections I tried to push the branch to the repo but I dont think I have permissions - hence the fork.
> I could just maintain a SP-124 branch on my GitHub and give the other folks access? I'll do whatever you think is easier to manage at your end.

This sounds really strange, you should be able to clone, branch and push the branch upstream. that would be my preferred workflow so I can easily pull and puch my commits to the PR. Are you logging in with the correct user as registered in the ska-telescope organisation?

**Comment by steve-ord** [comment]
@flyingfrog81 I don't have permissions to add a branch to the repo

"ska-telescope/developer.skatelescope.org.git denied to steve-ord" Can I be added - or would you rather I used the fork?

**Comment by flyingfrog81** [comment]
> @flyingfrog81 I don't have permissions to add a branch to the repo
> 
> "ska-telescope/developer.skatelescope.org.git denied to steve-ord" Can I be added - or would you rather I used the fork?

Sorry for this @steve-ord ! I had messed up the repo permissions ... now everything should be in order for you to create the branch. Again, I'm really sorry this might have slowed you down.

**Comment by steve-ord** [comment]
ok can now push to the repo - will close this pull request and reopen one on the branch after adding the boilerplate

**Pull request closed without merging**
